# Generated by Django 4.2.11 on 2026-08-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
